name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/smart-gym-monitoring-system

            #  Fix git conflicts
            git reset --hard
            git clean -fd
            git pull origin main

            #  Go to Django project
            cd django_backend/gym_backend

            #  Activate virtual environment
            source venv/bin/activate

            #  Install dependencies (FIXED PATH)
            pip install -r ../../requirements.txt

            #  Run migrations
            python3 manage.py migrate --noinput

            #  Collect static files
            python3 manage.py collectstatic --noinput

            #  Restart services
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx